### ISSUE TITLE
How to achieve scroll as smooth as Firefox ? 

### ISSUE THREAD

**Issue by zubairanwar2** [im4aLL/chromeSmoothScroll#1]
I had a question regarding the plugin. How can I make the scroll as smooth as firefox ? you see the default scroll is Kinda cool and has a smooth bouncy scroll effect however I want to achieve scrolling as smooth as Firefox. How do I achieve that ? what variables should I play with to get the desired effect ?

**Comment by im4aLL** [comment]
Sorry for late reply! I was out of town.

I have added Firefox smooth scroll. You can turn it on for here - 

in chromeSmoothScroll.js

``` javascript
var settings = {
   chromeOnly : true
}
```

default its sets to true, you need to set it false in order to work in firefox! Please let me know if there is any problem. BTW check latest commit
